# Generated by Django 2.2.2 on 2019-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_remove_socialprovider_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='providers',
            field=models.ManyToManyField(blank=True, to='providers.SocialProvider'),
        ),
    ]
