# Generated by Django 2.2.2 on 2019-06-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_socialprovider_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprovider',
            name='users',
        ),
    ]
