# Generated by Django 2.2.2 on 2019-07-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_socialprovider_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprovider',
            name='token',
        ),
    ]
