# Generated by Django 2.2.2 on 2019-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymetric',
            name='click',
        ),
        migrations.RemoveField(
            model_name='dailymetric',
            name='view',
        ),
        migrations.RemoveField(
            model_name='weeklymetric',
            name='impression',
        ),
        migrations.RemoveField(
            model_name='weeklymetric',
            name='reach',
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='type',
            field=models.CharField(choices=[('click', 'click'), ('view', 'view')], default='click', max_length=250),
        ),
        migrations.AddField(
            model_name='weeklymetric',
            name='type',
            field=models.CharField(choices=[('reach', 'reach'), ('impression', 'impression')], default='impression', max_length=250),
        ),
    ]
