# Generated by Django 2.2.2 on 2019-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_auto_20190707_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklymetric',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
